### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by sagikazarmark** [sagikazarmark/fsig#1]
- [x] Add alternatives (tools and scripts)
- [x] Add instructions for docker install
- [x] Improve tests
- [x] Add version with ldflags
- [x] Push binaries to Github
- [x] Accept string signals like SIGHUP or HUP (support the most common codes and platforms, like linux and mac)
